### PR TITLE
Just a little bit of changes

### PR DESCRIPTION
**Pull request by yhetman**
I suggest you to use uint32_t for width and height in BMPFileHeader instead of int32_t as by default images can't have negative widths and heights, usage of int32_t can cause unexpected runtime errors.
After compilation of code I faced a Warning: # pragma once in main file (I used g++ -std=c++11), thus to make it more eye-candy I replaced it with # ifndef C-routine in BMP.h.
Also, I added typedef-s for all structs except BMP itself.
P.S. Very cool and useful repo, like the way it was written ;)

### CODE REVIEW

**Comment by sol-prog** [comment]
Hello Yuliia,

thanks for contributing.

* I've used int32_t and not uint32_t for width because this what the Microsoft specifications for these two fields requires. Please check BITMAPINFOHEADER after Windows 2000 from https://en.wikipedia.org/wiki/BMP_file_format.
* What version of G++ are you using ? I never got a warning for pragma although I always use *-std=c++17 -Wall -Wextra -pedantic*. It is true that pragma once is not standard, but it is accepted by all modern C++ compilers. In the end it is a question of programming style, some people prefer ifndef, other people prefer to use pragma once.
* typedef is more of a C style than C++ style, in modern C++ we tend to use *using*.

Regards,
Paul

**Comment by yhetman** [comment]
Hello, Paul!
Thanks for your explanation. I was using g++ -std=c++11 -Wall -Wextra -Werror then. 
Kind regards, Yuliia.

**Comment by sol-prog** [comment]
Hello Yuliia,

can you please run:

```
g++ --version
```

on your machine and let me know the *version* number of the compiler ? I assume you are doing your tests on a Linux machine ?
Thanks,
Paul

**Comment by sol-prog** [comment]
I want to see if I can replicate your error/warning about using pragma once.

**Comment by yhetman** [comment]
Hello, Paul!
Result after running `g++ --version` : 
```console
g++ (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kescherCode** [comment]
Another fine example of why I despise Ubuntu in the wild. Current g++ version would be 11.

**Comment by kescherCode** [comment]
You see the copyright date of 2015? You also see @sol-prog's flag: -std=c++17? This is why you see this weird warning.

**Comment by sol-prog** [comment]
Thanks Yuliia,

I have an old server at work that is still using 16.04. It is not used for C++ dev, but for Python dev with Anaconda where you can have latest Python version on older operating system without any problem, so nobody bothered to update the OS.

BTW, feel free to use ifndef on your machine to silence the compiler.

**Pull request closed without merging**
